let nombreInstructor = "Nico Isnardi";
let alturaInstructor = null;
let EstAprox = 27;
let SeAprendeJavascript = true;
let SeAprendePython = false;
let FechaCertificado = undefined;

console.log("Nombre del instructor: ",nombreInstructor);
console.log("Altura del insctructor: ",alturaInstructor);
console.log("Número aproximado de estudiantes: ",EstAprox);
console.log("¿Se aprende Javascript?: ",SeAprendeJavascript);
console.log("¿Se aprende python?: ",SeAprendePython);
console.log("Fecha de emisión del certificado: ",FechaCertificado);
console.log(" ");
console.log("Nombre del instructor: ",typeof nombreInstructor);
console.log("Altura del insctructor: ",typeof alturaInstructor);
console.log("Número aproximado de estudiantes: ",typeof EstAprox);
console.log("Se aprende Javascript: ",typeof SeAprendeJavascript);
console.log("Se aprende python: ",typeof SeAprendePython);
console.log("Fecha de emisión del certificado: ",typeof FechaCertificado);